### ISSUE TITLE
Create a Prod environment

### ISSUE THREAD

**Issue by jakubgs** [dap-ps/infra-dapps#1]
We will need a proper prod environment for release of https://dap.ps/.

Things we will need:

### Vital
* [x] #2 - SSL Certificate that we can use with Elastic Load Balancer
* [x] #3 - Elastic Load Balancer for balancing load
* [x] #5 - Scalability with load
* [x] #6 - MongoDB cluster
* [x] #7 - Backups for MongoDB

### Optional

* [ ] #4 - Geographically spread hosts
* [x] #10 - Periodic EC2 snapshots
* [ ] #11 - WebUI for MongoDB

---

This is enough for for a week if I have nothing else to do.
Especially with the scalability and geographical spread.

**Comment by jakubgs** [comment]
I have [verified](https://github.com/dap-ps/infra-dapps/issues/5#issuecomment-517285363) that the ElasticBeanstalk environment does scale with CPU load.

**Comment by jakubgs** [comment]
I have finished deploying the prod MongoDB replication set(cluster) and [verified it's working](https://github.com/dap-ps/infra-dapps/issues/6#issuecomment-517404182).

I've updated the `DB_CONNECTION` environment variable in the `prod-dap-ps-app` so it's ready.

**Comment by jakubgs** [comment]
I fixed the absolute paths generated by Embark by hand(well, mostly with `sed`) and deployed that to Dev environment and it is up right now: https://dev.dap.ps/

But when I tried submitting my Dapp I got back:
```
A DApp was not uploaded in the client
```
And here's the reason:
![blocked_content](https://user-images.githubusercontent.com/2212681/62320835-41cf8780-b46f-11e9-9e14-36a24fa81aab.png)
Looks like the `/metadata` request is made to http://dev.dap.ps/metadata, not using HTTPS.

**Comment by jakubgs** [comment]
I've prepared some fixes for the app itself: https://github.com/dap-ps/discover/pull/25

And once I have some funds for the `0x9fb115BC152aE21ECDc81c73843673fa38e4D2dB` contract I can try creating a submission.

**Comment by jakubgs** [comment]
Email sending issues fixed in https://github.com/dap-ps/infra-dapps/issues/9.

**Comment by jakubgs** [comment]
Looks like it works:
![dapps_email](https://user-images.githubusercontent.com/2212681/62555680-5cc04400-b841-11e9-96d0-aae9f86879bf.png)

**Comment by jakubgs** [comment]
Yay, my TEH_REI crypto Dapp is up!
![teh_rei](https://user-images.githubusercontent.com/2212681/62570449-a4ed5f80-b85d-11e9-9374-e04a56775f96.png)
Glorious.
![1344438424705](https://user-images.githubusercontent.com/2212681/62570558-c64e4b80-b85d-11e9-809c-2c849aaa4eef.gif)

**Comment by jakubgs** [comment]
Updated the prod configuration with Mainnet contract deployed by Andy: d344fefb567b25c9517c5a91b36f3722caa39a2d

**Comment by jakubgs** [comment]
Okay, Apparently there is and environment variable named `EB_NODE_COMMAND` which is by default for Node.js just takes the value of the `start` task from `package.json`. I think if I set it explicitly for the environment I will be able to change `start` target to the old value of `./node_modules/.bin/react-scripts start`.

**Comment by jakubgs** [comment]
Brilliant, `create-react-app` is literally incapable for building a dev build with `react-scripts build`:
https://github.com/facebook/create-react-app/issues/2880
Which means I can't use [React Developer Tools](React Developer Tools) with https://dev.dap.ps/ because I can't build a dev build for it.
The retardation never stops.
![the it crowd - facepalm](https://user-images.githubusercontent.com/2212681/62640637-07069d00-b910-11e9-8faa-57ba944906e3.jpeg)

**Comment by jakubgs** [comment]
Also we are getting `403` from a request to `ipfs.infura.io`:
```
https://ipfs.infura.io:5001/api/v0/id?stream-channels=true
ipfs method not allowed
```
No clue what that is about.

**Comment by jakubgs** [comment]
Mixed content issue: #12

**Comment by jakubgs** [comment]
@andytudhope looks like you broke this application in
https://github.com/dap-ps/discover/commit/433afcef66d59fbaa7684c3272950e2629fcab5f#diff-5e5eb47cd24f028b901ce69c09dcaa14R1

You replaced:
```js
const wallet = require('./development/mnemonic')
```
With:
```js
const wallet = require('./livenet/mnemonic')
```
But there is no such thing as `config/livenet`:
https://github.com/dap-ps/discover/tree/master/config/livenet

How is this supposed to work?

**Comment by jakubgs** [comment]
@andytudhope also, why are you merging PRs like https://github.com/dap-ps/discover/pull/28 without me reviewing them first? What's the point of making a PR if nobody is going to review it? You might as well commit directly to `master` if you don't wait for reviews.

**Comment by andytudhope** [comment]
sorry, you're right. Will change that back.

**Comment by andytudhope** [comment]
> Also we are getting 403 from a request to ipfs.infura.io:

This is because there is a bug in Embark which means that you have to change the embarkjs.js file generated in `src/embarkArtifacts` after running `embark build` (it's detailed in the README). I know it's a nasty AF hack, but there really is no way around it, and the Embark team have yet to release 4.1 with the fix...

**Comment by jakubgs** [comment]
Replacement of `build.sh` with a `Makefiles`: https://github.com/dap-ps/discover/pull/3

**Comment by jakubgs** [comment]
Mixed content issue #12 fixed in https://github.com/dap-ps/discover/pull/7.

**Comment by jakubgs** [comment]
Yet another issue that needed fixing: https://github.com/dap-ps/discover/issues/9
Not handling paths that are not in `frontend` folder on the backend.
And the fix: https://github.com/dap-ps/discover/pull/10

**Comment by jakubgs** [comment]
There is one more thing I need to do.. Currently the certificate issues by AMC only handles the specific domain in question:
https://github.com/dap-ps/infra-dapps/blob/d344fefb567b25c9517c5a91b36f3722caa39a2d/modules/aws-eb-env/cert.tf#L1-L7
So I need to modify this to include `dap.ps`. Either as a SAN or make it the main domain and add the `*.dap.ps` subdomains as SANs.

I also have two options:

* Both certificates for dev and prod should include `dap.ps` as a SAN
* Only prod certificate will include `dap.ps` in valid domains

The first option would allow us to point `dap.ps` at `dev.dap.ps`, not sure if would want to do that.

**Comment by jakubgs** [comment]
Okay, I've re-created the Prod env with the certificate that includes the `dap.ps` domain in the SANs:
![prod_dap_ps_cert](https://user-images.githubusercontent.com/2212681/62794104-3e588380-baa1-11e9-878e-ee45393efb74.png)
Here's the change: d6853ee6b46a058509bf75f5c5376378de8eb267
But I will have to do the same thing to Dev, which will make it unavailable for a while.

**Comment by jakubgs** [comment]
Both certs have been re-issued with `dap.ps` in their SANs:
![new_dap_ps_certs](https://user-images.githubusercontent.com/2212681/62806122-f09f4380-babf-11e9-86ed-b697ccd81ad6.png)

**Comment by jakubgs** [comment]
As we have prod up and running, can I close this @andytudhope ? I have the other 3 optional issues open.

**Comment by andytudhope** [comment]
Yeah, just that there is an error on prod.dap.ps/metadata/all still and I'm not sure why...

**Comment by jakubgs** [comment]
That was due to lack of `?replicaSet=` argument in the URI in `DB_CONNECTION` env in prod, fixed.
